version: '3'
services:
  rails:
    build: .
    image: woto
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    stdin_open: true
    tty: true
    depends_on:
      - "postgres"
    command: ./docker-entrypoint-rails.sh
  webpacker:
    image: woto
    command: ./docker-entrypoint-webpacker.sh
    volumes:
      - .:/rails
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
      - "rails"
  postgres:
    image: "postgres:9.6.3"
    environment:
      - POSTGRES_USER=busfor
      - POSTGRES_PASSWORD=busfor
