version: '3'
services:
  rails:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - .:/rails
    stdin_open: true
    tty: true
  postgres:
    image: "postgres:9.6.3"
    environment:
      - POSTGRES_USER=busfor
      - POSTGRES_PASSWORD=busfor
